# Generated by Django 4.2.4 on 2023-10-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0004_configdashboard_u_gdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbprophet_forecasts',
            name='model',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
