# Generated by Django 4.2.4 on 2023-10-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_fbprophet_forecasts_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbprophet_forecasts',
            name='model',
            field=models.CharField(default='No path', max_length=255),
            preserve_default=False,
        ),
    ]
