# Generated by Django 4.2.4 on 2023-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_alter_fbprophet_forecasts_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='arima_forecasts',
            name='plot_arima',
            field=models.CharField(default='Not defined', max_length=255),
            preserve_default=False,
        ),
    ]
