# Generated by Django 4.1.7 on 2023-09-30 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arima_forecasts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fbprophet_forecasts',
            name='user',
        ),
        migrations.RemoveField(
            model_name='geodataframe',
            name='user',
        ),
        migrations.AddField(
            model_name='arima_forecasts',
            name='U_df',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.uploaded_dataframe'),
        ),
        migrations.AddField(
            model_name='fbprophet_forecasts',
            name='U_df',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.uploaded_dataframe'),
        ),
        migrations.AddField(
            model_name='geodataframe',
            name='U_df',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.uploaded_dataframe'),
        ),
    ]
