# Generated by Django 4.2.4 on 2023-09-26 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myfilemodel',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
