# Generated by Django 4.2.4 on 2023-10-02 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_configdashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='configdashboard',
            name='U_gdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.geodataframe'),
        ),
    ]
