# Generated by Django 4.2.4 on 2023-09-27 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualization', '0006_geodataframe_uploaded_dataframe_delete_myfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='fbProphet_forecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtered_by', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads_fb_forecasts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
