# Generated by Django 4.2.4 on 2023-09-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0008_arima_forecasts'),
    ]

    operations = [
        migrations.AddField(
            model_name='arima_forecasts',
            name='period',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fbprophet_forecasts',
            name='period',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
