# Generated by Django 4.2.4 on 2023-09-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0009_arima_forecasts_period_fbprophet_forecasts_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbprophet_forecasts',
            name='frequency',
            field=models.CharField(default='years', max_length=255),
            preserve_default=False,
        ),
    ]
